// api/generate-video.js — Vercel serverless handler for /api/generate-video
//
// Accepts POST { prompt, userId, plan, sessionId,
//                referenceImages, referenceFidelity, referenceLockVideoMode, hasReferenceImage }
//   prompt                : text description / scene / motion instructions (string, required)
//   userId                : authenticated user ID or 'guest' (string, optional)
//   plan                  : subscription plan name (string, optional)
//   sessionId             : anonymous session ID (string, optional)
//   referenceImages       : array of { data: string, mimeType: string } — uploaded reference
//                           images that define the subject to animate (optional)
//   referenceFidelity     : 'balanced' | 'high' | 'exact' — controls how closely the
//                           generated video concept preserves the reference.  When omitted
//                           the value is derived from referenceLockVideoMode / prompt
//                           auto-detection.  Defaults to 'high' when reference images are
//                           present. (optional)
//   referenceLockVideoMode: boolean — activates REFERENCE_LOCK_VIDEO_MODE which preserves
//                           the uploaded subject's identity and design during motion
//                           generation. (optional)
//   hasReferenceImage     : boolean — convenience flag signalling that at least one
//                           reference image is present; used as a secondary activation
//                           signal when referenceLockVideoMode is not explicitly set.
//                           (optional)
//
// REFERENCE_LOCK_VIDEO_MODE behaviour:
//   When active, the endpoint:
//     1. Validates reference images.
//     2. Calls GPT-4o Vision to produce a structured design analysis of the
//        primary reference image (design blueprint).
//     3. Builds a reference-locked video concept prompt that instructs the
//        model to preserve the uploaded subject's identity, design, silhouette,
//        and key visual features while applying only the requested motion or
//        scene changes.
//     4. Uses GPT-4o to generate a detailed, frame-accurate video concept /
//        storyboard description that is faithful to the reference — ready for
//        use with a dedicated video generation API when one is configured.
//
// The endpoint returns:
//   { concept: string, prompt: string, referenceLocked: boolean }
//
//   concept       : A rich video scene / storyboard description generated by
//                   GPT-4o, faithful to the reference when referenceLocked is true.
//   prompt        : The final prompt sent to the generation model.
//   referenceLocked: true when REFERENCE_LOCK_VIDEO_MODE was active for this request.
//
// The existing /api/chat and /api/generate-image endpoints are NOT modified.

'use strict';

// Usage limits helper — loaded lazily so a missing / misconfigured module
// never blocks the video generation flow.
let _usageLimits = null;
try {
  _usageLimits = require('../lib/usageLimits');
} catch (e) {
  console.warn('api/generate-video: usage limits unavailable:', e.message);
}

// Allowed reference fidelity levels (mirrors api/generate-image.js).
const ALLOWED_FIDELITY = ['balanced', 'high', 'exact'];

// Maximum characters for the user prompt field (sanitization guard).
// The reference-locked prompt is built on top of this and sent to GPT-4o,
// which supports much larger context than DALL-E 3, so no secondary truncation
// is applied to the fully-assembled locked prompt.
const MAX_PROMPT_LENGTH = 4000;

// Pattern for validating data URLs containing base64-encoded images.
const DATA_URL_PATTERN = /^data:image\/[a-z0-9.+-]+;base64,/i;

// Regex patterns that indicate a strict fidelity request in the user's prompt.
// Kept in sync with api/generate-image.js STRICT_FIDELITY_PATTERNS.
const STRICT_FIDELITY_PATTERNS = [
  /\bexact(ly)?\b/i,
  /\bdo\s*not\s*change\b/i,
  /\bdon'?t\s*change\b/i,
  /\bpreserve\s*this\b/i,
  /\bsame\s*design\b/i,
  /\bmake\s*this\s*realistic\b/i,
  /\buse\s*this\s*exact\b/i,
  /\bkeep\s*the\s*design\b/i,
  /\bput\s*this\s*on\b/i,
  /\bmake\s*this\s*real\b/i,
  /\bturn\s*this\s+(?:drawing|sketch|design|image)\b/i,
  /\bno\s*changes?\b/i,
  /\bfaithful(ly)?\b/i,
  /\bfidelity\b/i,
  /\baccurate(ly)?\b/i,
  /\banimate\s*this\b/i,
  /\bbring\s*this\s*to\s*life\b/i,
];

/**
 * Returns true when the prompt text contains language that strongly requests
 * high-fidelity reproduction of a reference image in a video context.
 *
 * @param {string} prompt
 * @returns {boolean}
 */
function detectStrictFidelityMode(prompt) {
  if (!prompt || typeof prompt !== 'string') return false;
  return STRICT_FIDELITY_PATTERNS.some(function (re) { return re.test(prompt); });
}

/**
 * Calls GPT-4o Vision to produce a structured design analysis of the primary
 * reference image.  The analysis is used to build a reference-locked video prompt.
 *
 * @param {string} apiKey          OpenAI API key
 * @param {{ data: string, mimeType: string }[]} referenceImages
 * @returns {Promise<string>}      Structured text description, or '' on failure
 */
async function analyzeReferenceImage(apiKey, referenceImages) {
  if (!referenceImages || referenceImages.length === 0) return '';

  // Build image_url parts for the analysis request.
  // Primary blueprint = first image; additional images included as supporting refs.
  const imageParts = referenceImages.slice(0, 4).map(function (img) {
    const mimeType = (img.mimeType || 'image/jpeg').split(';')[0].trim();
    const url = img.data.startsWith('data:') ? img.data : ('data:' + mimeType + ';base64,' + img.data);
    return { type: 'image_url', image_url: { url: url, detail: 'high' } };
  }).filter(function (part) {
    return DATA_URL_PATTERN.test(part.image_url.url) || /^data:image\//.test(part.image_url.url);
  });

  if (imageParts.length === 0) return '';

  const analysisMessages = [
    {
      role: 'system',
      content:
        'You are a precise visual design analyst. Examine the provided reference image(s) and produce a ' +
        'structured design description that will be used to guide a faithful video animation. ' +
        'Be concise but comprehensive. Focus only on visual/design attributes — no commentary.'
    },
    {
      role: 'user',
      content: [
        {
          type: 'text',
          text:
            'Analyze this reference image and describe its visual design for faithful video animation. ' +
            'Cover these attributes where applicable:\n' +
            '- Subject or object category\n' +
            '- Overall silhouette and outline shape\n' +
            '- Proportions and key dimensions\n' +
            '- Major color zones and color blocking\n' +
            '- Stripe, marking, or pattern layout\n' +
            '- Material or texture cues\n' +
            '- Structural elements, seams, and panels\n' +
            '- Facial features or identity markers (if a character or face)\n' +
            '- Edge shapes and profile\n' +
            '- Placement of distinctive features\n' +
            '- Motion potential — how this subject could naturally move\n\n' +
            'Output a concise structured description only. No preamble.'
        },
        ...imageParts
      ]
    }
  ];

  try {
    const visionRes = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + apiKey
      },
      body: JSON.stringify({
        model: 'gpt-4o',
        messages: analysisMessages,
        max_tokens: 600,
        temperature: 0.2
      })
    });
    if (!visionRes.ok) return '';
    const visionData = await visionRes.json();
    const content =
      visionData.choices &&
      visionData.choices[0] &&
      visionData.choices[0].message &&
      visionData.choices[0].message.content;
    return (typeof content === 'string' ? content.trim() : '');
  } catch (e) {
    console.warn('api/generate-video: reference image analysis failed:', e.message);
    return '';
  }
}

/**
 * Builds a reference-locked video concept prompt that instructs GPT-4o to
 * treat the reference design as the authoritative visual blueprint while
 * using the user's text only for scene / motion / context.
 *
 * @param {string} userPrompt       Original text from the user
 * @param {string} designAnalysis   Structured design description from GPT-4o Vision
 * @param {boolean} hasMultipleRefs Whether secondary reference images were provided
 * @param {string} [fidelityLevel]  'high' (default) or 'exact' for maximum preservation
 * @returns {string}
 */
function buildReferenceLockVideoPrompt(userPrompt, designAnalysis, hasMultipleRefs, fidelityLevel) {
  const blueprintSection = designAnalysis
    ? 'SUBJECT DESIGN BLUEPRINT (from uploaded reference image):\n' + designAnalysis
    : 'SUBJECT DESIGN BLUEPRINT: Follow the uploaded reference image exactly as the design source.';

  const secondaryNote = hasMultipleRefs
    ? '\nSecondary reference image(s) may provide material, realism, or lighting guidance but must NOT override the primary subject design.'
    : '';

  const isExact = fidelityLevel === 'exact';

  const header = isExact
    ? '[REFERENCE_LOCK_VIDEO_MODE — EXACT PRESERVATION — DO NOT ALTER SUBJECT DESIGN]\n\n'
    : '[REFERENCE_LOCK_VIDEO_MODE — PRESERVE SUBJECT IDENTITY AND DESIGN]\n\n';

  const extraExactConstraints = isExact
    ? '- EXACT mode: treat every visual detail of the uploaded subject as mandatory.\n' +
      '- EXACT mode: do not simplify, stylize, or reinterpret any part of the subject.\n' +
      '- EXACT mode: only apply the requested motion, scene, or environment changes.\n' +
      '- EXACT mode: preserve character or object identity throughout all frames.\n'
    : '';

  const videoConceptInstruction =
    '\n\nTASK: Generate a detailed, frame-accurate video concept / storyboard description for this subject. ' +
    'Describe the video scene, camera movement, motion, and environment as requested — while ensuring the ' +
    'uploaded subject appears exactly as designed throughout every frame of the video. ' +
    'Structure the output as: [Scene Overview] → [Key Frames] → [Motion Description] → [Camera & Lighting].';

  return (
    header +
    blueprintSection +
    secondaryNote +
    '\n\nSCENE / MOTION INSTRUCTION (from user):\n' + userPrompt +
    '\n\nCRITICAL VIDEO RULES — DO NOT DEVIATE:\n' +
    '- The uploaded reference image IS the subject. Animate it faithfully — do not replace it.\n' +
    '- Preserve the subject\'s silhouette, design, proportions, and identity across all frames.\n' +
    '- Preserve all color zones, markings, and design elements throughout the animation.\n' +
    '- Apply motion to the uploaded subject — do not generate a different-looking version.\n' +
    '- Only add the requested scene context, environment, lighting, and motion.\n' +
    '- DO NOT redesign or reinterpret the uploaded subject.\n' +
    '- DO NOT substitute the subject with a more cinematic, generic, or standard variant.\n' +
    '- DO NOT use the reference as loose inspiration — it is the design blueprint.\n' +
    '- Bias strongly toward identity preservation over stylistic creativity.\n' +
    extraExactConstraints +
    '\nNEGATIVE CONSTRAINTS: do not change silhouette; do not alter proportions; do not add unrequested ' +
    'features; do not replace subject identity; do not drift from source design between frames.' +
    videoConceptInstruction
  );
}

/**
 * Calls GPT-4o to generate a detailed video concept / storyboard description.
 * When reference lock is active the prompt is pre-loaded with the design blueprint
 * and strict preservation rules.
 *
 * @param {string} apiKey
 * @param {string} finalPrompt  The (possibly fidelity-reinforced) generation prompt
 * @param {boolean} isLocked    Whether reference lock mode is active
 * @returns {Promise<string>}   Generated video concept text
 */
async function generateVideoConcept(apiKey, finalPrompt, isLocked) {
  const systemContent = isLocked
    ? 'You are a precise video director specializing in faithful, reference-locked animation. ' +
      'Your role is to produce a detailed, frame-accurate video concept that exactly preserves ' +
      'the uploaded subject\'s design and identity while applying only the requested motion and scene. ' +
      'Follow all REFERENCE_LOCK_VIDEO_MODE rules strictly. ' +
      'Do NOT redesign or replace the subject. Output only the video concept description.'
    : 'You are a creative video director. Produce a detailed video concept / storyboard description ' +
      'based on the user\'s instructions. Describe scene, motion, camera, and lighting clearly. ' +
      'Output only the video concept description.';

  const messages = [
    { role: 'system', content: systemContent },
    { role: 'user', content: finalPrompt }
  ];

  const genRes = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer ' + apiKey
    },
    body: JSON.stringify({
      model: 'gpt-4o',
      messages: messages,
      max_tokens: 1200,
      temperature: isLocked ? 0.3 : 0.7
    })
  });

  if (!genRes.ok) {
    let errData;
    try { errData = await genRes.json(); } catch (e) { errData = null; }
    const msg = (errData && errData.error && errData.error.message) || 'Video concept generation failed';
    throw new Error(msg);
  }

  const genData = await genRes.json();
  const content =
    genData.choices &&
    genData.choices[0] &&
    genData.choices[0].message &&
    genData.choices[0].message.content;
  return typeof content === 'string' ? content.trim() : '';
}

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Content-Type', 'application/json');
    return res.status(405).json({ error: { message: 'Method not allowed' } });
  }

  try {
    const {
      prompt,
      userId,
      plan,
      sessionId,
      referenceImages,
      referenceFidelity,
      referenceLockVideoMode,
      hasReferenceImage
    } = req.body || {};

    // ── Input validation ────────────────────────────────────────────────────

    if (!prompt || typeof prompt !== 'string' || !prompt.trim()) {
      res.setHeader('Content-Type', 'application/json');
      return res.status(400).json({ error: { message: 'prompt (string) is required' } });
    }

    // Sanitize prompt: trim whitespace and limit length.
    const safePrompt = prompt.trim().slice(0, MAX_PROMPT_LENGTH);

    // ── Daily video generation quota ────────────────────────────────────────

    if (_usageLimits) {
      const trackingId = (userId && userId !== 'guest') ? userId : sessionId;
      if (trackingId) {
        try {
          const KNOWN_PLANS = Object.keys(_usageLimits.PLAN_LIMITS);
          const rawPlan = typeof plan === 'string' ? plan.toLowerCase() : '';
          const userPlan = KNOWN_PLANS.includes(rawPlan) ? rawPlan : 'starter';
          const result = await _usageLimits.checkAndTrack(trackingId, userPlan, 'video');
          if (!result.allowed) {
            res.setHeader('Content-Type', 'application/json');
            return res.status(429).json({
              error: { message: result.error || 'Daily video generation limit reached. Upgrade your plan or wait for the reset.' }
            });
          }
        } catch (e) {
          // Usage limit check failure is non-fatal — let the request proceed.
          console.warn('api/generate-video: usage limit check failed:', e.message);
        }
      }
    }

    // ── Reference lock mode resolution ─────────────────────────────────────
    // Normalise the reference images list.
    const refImageList = [];
    if (Array.isArray(referenceImages) && referenceImages.length > 0) {
      referenceImages.forEach(function (img) {
        if (
          img &&
          typeof img === 'object' &&
          typeof img.data === 'string' &&
          img.data.length > 0 &&
          (DATA_URL_PATTERN.test(img.data) || /^[A-Za-z0-9+/]/.test(img.data))
        ) {
          refImageList.push(img);
        }
      });
    }

    // hasReferenceImage can be set explicitly or derived from the images list.
    const hasRefImages = refImageList.length > 0 || hasReferenceImage === true;

    // Resolve the effective fidelity level (mirrors api/generate-image.js logic).
    //   1. Use the explicit referenceFidelity parameter when it is a valid value.
    //   2. Fall back to referenceLockVideoMode boolean or prompt auto-detection.
    //   3. When reference images are present, default to 'high'.
    //   4. Otherwise keep 'balanced'.
    let effectiveFidelity = 'balanced';
    if (ALLOWED_FIDELITY.includes(referenceFidelity)) {
      effectiveFidelity = referenceFidelity;
    } else if (hasRefImages && (referenceLockVideoMode === true || detectStrictFidelityMode(safePrompt))) {
      effectiveFidelity = 'high';
    } else if (hasRefImages && referenceLockVideoMode !== false) {
      // Reference images present but no explicit lock flag — default to 'high'.
      // Callers that explicitly pass referenceLockVideoMode: false opt out.
      effectiveFidelity = 'high';
    }

    // REFERENCE_LOCK_VIDEO_MODE is active when reference images are present
    // and fidelity is not 'balanced'.
    const isLockMode = hasRefImages && effectiveFidelity !== 'balanced';

    if (isLockMode) {
      console.log(
        'api/generate-video: REFERENCE_LOCK_VIDEO_MODE ACTIVE (' + effectiveFidelity + ') — ' +
        refImageList.length + ' reference image(s), prompt snippet: "' +
        safePrompt.slice(0, 80) + '"'
      );
    }

    // ── OpenAI API call ─────────────────────────────────────────────────────

    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      res.setHeader('Content-Type', 'application/json');
      return res.status(500).json({ error: { message: 'API key not configured' } });
    }

    // When reference lock mode is active, analyse the reference image with
    // GPT-4o Vision to derive a structured design description, then build a
    // reference-locked prompt for the video concept generator.
    // Note: no secondary truncation is applied to the assembled locked prompt
    // because GPT-4o (unlike DALL-E 3) supports large context inputs.
    let finalPrompt = safePrompt;
    if (isLockMode && refImageList.length > 0) {
      const designAnalysis = await analyzeReferenceImage(apiKey, refImageList);
      finalPrompt = buildReferenceLockVideoPrompt(
        safePrompt,
        designAnalysis,
        refImageList.length > 1,
        effectiveFidelity
      );
    }

    // Generate the video concept description using GPT-4o.
    const concept = await generateVideoConcept(apiKey, finalPrompt, isLockMode);

    if (!concept) {
      res.setHeader('Content-Type', 'application/json');
      return res.status(502).json({ error: { message: 'No video concept returned from generation service' } });
    }

    res.setHeader('Content-Type', 'application/json');
    return res.status(200).json({
      concept: concept,
      prompt: safePrompt,
      referenceLocked: isLockMode
    });
  } catch (err) {
    console.error('api/generate-video error:', err);
    if (!res.headersSent) {
      res.setHeader('Content-Type', 'application/json');
      return res.status(500).json({ error: { message: err.message || 'Internal server error' } });
    }
  }
};
